### ISSUE TITLE
Fails on invalid markup (malformed lists)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [txt2tags/txt2tags#173]
```
printf "title\nauthor\ndate\n: one\n two\n - three\n- four" | ./txt2tags -t 
html -i-

Sorry! Txt2tags aborted by an unknown error.
Please send the following Error Traceback to the author (verde@aurelio.net):

Traceback (most recent call last):
  File "./txt2tags", line 9620, in <module>
    exec_command_line()
  File "./txt2tags", line 9614, in exec_command_line
    convert_this_files(infiles_config)
  File "./txt2tags", line 8185, in convert_this_files
    target_body, marked_toc = convert(source_body, myconf, firstlinenr=first_body_line)
  File "./txt2tags", line 9111, in convert
    ret.extend(BLOCK.blockout())
  File "./txt2tags", line 6386, in blockout
    result = getattr(self, blockname)()
  File "./txt2tags", line 6843, in deflist
    return self.list('deflist')
  File "./txt2tags", line 6914, in list
    z, term, rest = item[0].split(SEPARATOR, 2)
ValueError: need more than 2 values to unpack
```

Original issue reported on code.google.com by `jendriks...@gmail.com` on 28 Feb 2013 at 12:54

**Comment by aureliojargas** [comment]
I confirm that this is still an issue, in both HEAD commits for branches v2 and v3.
