### ISSUE TITLE
 Ugly message when running only txt2tags

### ISSUE THREAD

**Issue by brunorusso** [txt2tags/txt2tags#233]
When I run txt2tags without any parameter the ugly message is shown

 $txt2tags
Traceback (most recent call last):
  File "/usr/local/bin/txt2tags", line 8, in <module>
    sys.exit(exec_command_line())
  File "/usr/local/lib/python3.8/dist-packages/txt2tags.py", line 4860, in exec_command_line
    Error(
  File "/usr/local/lib/python3.8/dist-packages/txt2tags.py", line 1833, in Error
    raise error(msg)
txt2tags.error: txt2tags: Error: Pass exactly one input file (see --help). Example: txt2tags -t html file.t2t

I think that the best message would: 

Use txt2tags -t html file.t2t
see --help for more information

I'm using
$ txt2tags -V
txt2tags version 3.7 <https://txt2tags.org>

thanks

**Comment by jendrikseipp** [comment]
I agree. If you're a developer, feel free to make a pull request.
